removing the check for consensus committee Byzantine threshold
onflow/flow-go pull request #1373
Opened 2021-09-28 19:10 UTC by vishalchangrani

For the consensus node test which has a 79 external partner consensus nodes and only 46 of our nodes, the finalize command fails with the error: 
`FTL will not bootstrap configuration without Byzantine majority of consensus nodes`
This assumption of the internal nodes having a majority will no longer be true starting from the next spork, hence this change to remove that check.

2021-09-28 19:22 UTC, jordanschalm commented
This has a bit of overlap with https://github.com/onflow/flow-go/pull/1371. Yurii already split the SN/LN constraints

2021-09-28 19:29 UTC, smnzhu approved these changes

2021-09-29 15:15 UTC, huitseeker requested changes
We also need to edit the check applied to collection clusters (around `if clusterInternalCount <= clusterPartnerCount*2`)

2021-09-29 15:15 UTC, huitseeker commented on cmd/bootstrap/cmd/constraints.go
> -			"will not bootstrap configuration without Byzantine majority of consensus nodes: "+
This should probably have been "Byzantine-resistant majority".

2021-09-29 17:31 UTC, vishalchangrani commented
closing this PR since [this PR](https://github.com/onflow/flow-go/pull/1371) takes care of this change

2021-09-29 17:31 UTC, closed without merging