Add checks to chunkVerifier.verifyTransactions
onflow/flow-go pull request #148
Opened 2020-11-13 09:22 UTC by arrivets

This PR addresses issue [4219](https://github.com/dapperlabs/flow-go/issues/4219)

The logic for verifying faulty computations was already there. I just completed a few
of the TODOs that were in the verifyTransactions function:

* Check ChunkDataPack.ChunkID corresponds to the proper Chunk
* Check ChunkDataPack.CollectionID is consistant with the Collection

2020-12-01 04:42 UTC, AlexHentschel requested changes
I am not quite sure what the precise scope of the ticket  [4219](https://github.com/dapperlabs/flow-go/issues/4219). There is a [comment on the corresponding Epic](https://github.com/dapperlabs/flow-go/issues/4111#issuecomment-713796251):

> - Do we have a common template to use when reporting these offenses? - Use log messages, that would all go to 1 shared 'list'. The log message should include keyword/s on how to easily identify them. Ensure that we log the 1) Original sender of the message. 
> - Should we use a uniform API for all nodes, or start with separate APIs for each? - We should stay away from a common approach. Use specific separate APIs for each node.

To the best of my understanding, to goal is:
1. introduce an API (node specific, or even component specific) which allows the business logic to report protocol violations to (including all the evidence collected)
2. inject an interface into the business logic and make the business logic report protocol violations to this API 
2. provide an implementation where this API is backed by a logger. Note: the logger should log at least on Warn level and have a common keyword that allows to filter for protocol violations.

2020-12-01 04:42 UTC, AlexHentschel commented on engine/verification/match/engine.go
> +	if collection.ID() != chunkDataPack.CollectionID {
I am generally wondering about the placement of this check. To me, it seems that it contains a special-case for the system chunk. However, I am generally concerned about simply basing this check on data the EN provides and could lie about: https://github.com/onflow/flow-go/blob/42c5833b218755cbe2b10300ca177445fbfe2f8e/engine/verification/match/engine.go#L463


Don't we have a check further down, where we determine whether we expect the chunk to be the system chunk or not (?): https://github.com/onflow/flow-go/blob/42c5833b218755cbe2b10300ca177445fbfe2f8e/engine/verification/match/engine.go#L504-L505

```golang
if isSystemChunk {
   // check that chunkDataPack.CollectionID is flow.ZeroID
   // VN knows how system chunk looks like: 
   //  * currently, system chunk is empty, i.e. we can check `collection.Len() == 0`
} else {
   // check that chunkDataPack.CollectionID is equal to the collection ID in the original block
}
```

I am worried about this check: `collection.Len() == 0`
To the best of my knowledge, the system chunk will contain transactions pretty soon (the transactions are protocol-determined instead; but they are still transactions I think). Therefore, I would suggest to create an issue: 
* include a factory for the system chunk which is shared between EN and VN
* VN uses the factory here to produce the collection that is supposed to be the system chunk (per protocol mandate). Subsequently, it checks that the `Checksum` of the expected system chunk collection matches the checksum of the collection provided by the EN.

@m4ksio do you have thoughts on this?

2020-12-03 21:21 UTC, ramtinms commented
Not sure if it is part of the scope of this issue, but another thing we discussed before but never got a chance to implement was to include chunk data pack ID (hash) inside the chunks and compare the hash of the incoming chunk data pack to check against that at verification node.

2021-11-23 19:28 UTC, j1010001 commented
most of the changes were integrated during the verification refactoring over the last year. Closing.

2021-11-23 19:28 UTC, closed without merging