[Execution] using valid descendents when loading unexecuted blocks
onflow/flow-go pull request #1588
Opened 2021-11-05 17:32 UTC by zhangchiqing

For https://github.com/dapperlabs/flow-go/issues/5989

The fixes an issue that the execution nodes are not loading only valid decendents on startup

2021-11-05 19:58 UTC, ramtinms approved these changes

2021-11-08 10:54 UTC, durkmurder requested changes
I believe this is not enough, unit tests are broken so we need to fix them. 
Mocks are expecting `Descendants` call not `ValidDescendants`

2021-11-12 10:29 UTC, durkmurder approved these changes
Nice, thanks for addressing this.

2021-11-12 17:37 UTC, zhangchiqing commented
bors merge

2021-11-12 17:55 UTC, merged