Add new code space for Canary addresses
onflow/flow-go pull request #2388
Opened 2022-05-09 18:46 UTC by tarakby

Add new code space for Canary addresses

2022-05-09 18:51 UTC, kc1116 approved these changes

2022-05-09 19:28 UTC, kc1116 requested changes
Need to update the unit tests

2022-05-09 20:56 UTC, kc1116 approved these changes

2022-05-12 15:46 UTC, jordanschalm approved these changes
Looks good 🎸 

I checked the `bootstrap` tool, and it looks like we don't need any additional changes there to be able to generate a root state for the new canary chain 👌

2022-05-12 17:44 UTC, tarakby commented
bors merge

2022-05-12 18:45 UTC, merged