Log MemoryUsed by transactions.
onflow/flow-go pull request #2396
Opened 2022-05-10 18:29 UTC by dsainati1

Add `MemoryUsed` to the transaction process, and then log it afterwards so we can pick it up in Grafana.

2022-05-10 20:18 UTC, janezpodhostnik requested changes

2022-05-10 20:18 UTC, janezpodhostnik commented on fvm/transaction.go
> +	proc.MemoryUsed = uint64(st.State().TotalMemoryUsed())
can you move this to `transactionInvoker` and duplicate the logic for computation used:
- https://github.com/onflow/flow-go/blob/8f7942581efe7d86f7f7121a7cb6c1daf9fd3499/fvm/transactionInvoker.go#L248
- https://github.com/onflow/flow-go/blob/8f7942581efe7d86f7f7121a7cb6c1daf9fd3499/fvm/transactionInvoker.go#L167

That way we have that logic together.

2022-05-11 14:21 UTC, janezpodhostnik approved these changes
LGTM

2022-05-12 17:52 UTC, SupunS approved these changes
Is it possible to add a test-case?

2022-05-12 17:52 UTC, SupunS commented on engine/execution/computation/computer/computer.go
> +		Uint64("memAlloc", memAllocAfter-memAllocBefore).
not something introduced in this PR, and probably not a big deal: wouldn't it be nice to use snake-case for all names for consistency? e.g: `memory_alloc`

2022-05-12 17:54 UTC, dsainati1 commented on fvm/fvm_test.go
> +			require.Greater(t, tx.MemoryUsed, uint64(20_000_000_000))
@SupunS should check that the `MemoryUsed` field is properly set/updated.

2022-05-12 17:55 UTC, dsainati1 commented on fvm/transactionInvoker.go
> +	proc.MemoryUsed = proc.MemoryUsed + memoryUsed
If our memory limit is lower than the max value for an integer, we should never have to worry about this overflowing right? The transaction should abort long before we near the point of overflow.

2022-05-12 22:47 UTC, merged

2022-06-20 03:39 UTC, SaveTheRbtz commented
Please note that `runtime.ReadMemStats` is a very expensive function to call since it calls `stopTheWorld` and waits for all goroutines to park:
```
// stopTheWorld stops all P's from executing goroutines, interrupting
// all goroutines at GC safe points and records reason as the reason
// for the stop. On return, only the current goroutine's P is running.
...
```