Add bitswap metrics
onflow/flow-go pull request #2932
Opened 2022-08-04 20:52 UTC by smnzhu

closes https://github.com/onflow/flow-go/issues/2679

2022-08-08 12:55 UTC, kc1116 approved these changes

2022-08-15 22:53 UTC, peterargue approved these changes
looks good. added one comment about logging

2022-08-15 22:53 UTC, peterargue commented on network/p2p/blob_service.go
> +						// TODO: log error
please add this

2022-08-15 23:07 UTC, SaveTheRbtz commented on network/p2p/blob_service.go
> +					metrics.Peers(prefix, len(stat.Peers))
it looks like prefix should be a property of the BitswapCollector instead of being passed to every function call.

2022-08-16 19:18 UTC, smnzhu commented
bors merge

2022-08-16 21:14 UTC, smnzhu commented
bors merge

2022-08-16 21:15 UTC, zhangchiqing commented on cmd/util/ledger/reporters/mock/report_writer.go
> +// Code generated by mockery v2.13.0. DO NOT EDIT.
I think you need to upgrade your mockery to `2.13.1`

2022-08-16 21:24 UTC, zhangchiqing requested changes
please upgrade your mockery to 2.13.1

2022-08-16 22:51 UTC, zhangchiqing approved these changes

2022-08-17 19:13 UTC, smnzhu commented
bors merge

2022-08-19 19:23 UTC, smnzhu commented
bors merge

2022-08-19 20:14 UTC, merged