[Benchmark] upload data to BigQuery directly
onflow/flow-go pull request #3241
Opened 2022-09-15 23:00 UTC by SaveTheRbtz

2022-09-16 18:28 UTC, pattyshack commented on integration/benchmark/cmd/ci/main.go
> +	bqClient, err := bigquery.NewClient(ctx, projectName)
i'm not familiar with the bigquery api.  do you need some sort of close / cleanup for the client / table?

2022-09-21 16:44 UTC, zhangchiqing approved these changes

2022-09-21 17:04 UTC, AndrewM-SDET requested changes
A couple of changes, some I will implement myself after the merge of https://github.com/onflow/flow-go/pull/3163 but all functional work looks good.

2022-09-21 17:04 UTC, AndrewM-SDET commented on .github/workflows/performance-ci.yml
> -  BIGQUERY_DATASET: production_src_flow_tps_metrics
This entire file can be removed, this yml now lives in dapperlabs/flow-go to make use of a private self-hosted runner. These changes are already implemented there.

2022-09-21 17:04 UTC, AndrewM-SDET commented on integration/benchmark/cmd/ci/main.go
> +	ProStartTransaction float64   `bigquery:"proStartTransaction"`
These will generate some conflicts when https://github.com/onflow/flow-go/pull/3163 is merged, I will push a fix for this.

2022-09-21 17:04 UTC, AndrewM-SDET commented on integration/benchmark/cmd/ci/main.go
> +	_ = flag.Bool("ci-run", false, "(deprecated)")
This is only referenced in integration/localhost/Makefile, we should remove it both in that file and here entirely.

2022-09-22 21:43 UTC, SaveTheRbtz commented
bors merge

2022-09-22 22:02 UTC, merged