[Metrics] Adding metrics interface for unweighted effort of ComputationKind
onflow/flow-go pull request #3388
Opened 2022-10-13 23:37 UTC by Tonix517

As the first step for #3312 - now we add metrics interface for the new unweighted computation effort of each block.

2022-10-14 15:49 UTC, janezpodhostnik requested changes

2022-10-14 17:32 UTC, Tonix517 commented on module/metrics.go
> +	ExecutionBlockComputationKindExecuted(string, uint)
addressed

2022-10-14 17:32 UTC, Tonix517 commented on module/metrics/execution.go
> +	blockComputationKinds               *prometheus.GaugeVec
addressed

2022-10-14 17:32 UTC, Tonix517 commented on module/metrics/execution.go
> +		Help:      "unweigthed effort of last execution block for given computation kind",
addressed

2022-10-17 20:38 UTC, janezpodhostnik approved these changes

2022-10-17 20:38 UTC, Tonix517 commented
bors merge

2022-10-17 20:59 UTC, Tonix517 commented
bors retry

2022-10-17 21:39 UTC, merged