Refactor get or load program
onflow/flow-go pull request #3976
Opened 2023-03-01 18:55 UTC by janezpodhostnik

Refactor GetAndSet (a.k.a. [GetOrLoad](https://github.com/onflow/cadence/pull/2362)) to make it easier to understand what is going on.

The next step is to remove the individual get and set methods, as they shouldn't be used anymore.

2023-03-01 19:05 UTC, pattyshack approved these changes

2023-03-01 19:07 UTC, pattyshack requested changes
could you rename the variables?  single letter variables aren't very readable

2023-03-02 16:56 UTC, janezpodhostnik commented
> could you rename the variables? single letter variables aren't very readable

Renamed, and fixed test. I hat to move the freeze check before the `get` part. 

The reason is that the freeze check touches registers, so it has to be done either the program is in cache or not.
The other solution to this is to put the freeze check into the nested state transaction, but I'll do that in the next PR.

2023-03-02 17:45 UTC, pattyshack approved these changes
thx for renaming

2023-03-02 23:12 UTC, zhangchiqing commented on fvm/environment/programs.go
> +		return nil, nil, fmt.Errorf("cannot set program. State was written to during program parsing")
```suggestion
		return nil, nil, fmt.Errorf("cannot set program to address %v. State was written to during program parsing", address)
```

2023-03-03 10:49 UTC, janezpodhostnik commented on fvm/environment/programs.go
> +		return nil, nil
I'm not actually sure why this is here. I kept it during the refactor as I did not want to change any logic to much. 

I will investigate why this is here and if we can remove it in a separate PR.

2023-03-03 11:03 UTC, janezpodhostnik commented on fvm/environment/programs.go
> +	}
see [above](https://github.com/onflow/flow-go/pull/3976/files#r1124297441)

2023-03-03 17:15 UTC, zhangchiqing commented on fvm/environment/programs.go
> +		return nil, nil
OK, maybe adding a TODO to remove it.

2023-03-03 17:15 UTC, zhangchiqing approved these changes

2023-03-06 15:45 UTC, janezpodhostnik commented
bors merge

2023-03-06 16:36 UTC, janezpodhostnik commented
bors merge

2023-03-06 18:48 UTC, janezpodhostnik commented
bors merge

2023-03-06 19:10 UTC, merged