Decouple transaction execution from result collection
onflow/flow-go pull request #4018
Opened 2023-03-08 20:06 UTC by pattyshack

1. flatten execution loop to operation directly on transactions, bypassing collections
2. change result collector to only operate on transaction result (and generate collection views internally)
3. change result collector to pipleine transaction processing

Note that I've purposely left result collector in a messy state to minimize the number of changes (most of the changes in result collector are just indent changes).  I'll go back to clean it up in a follow up PR.

2023-03-09 16:18 UTC, janezpodhostnik requested changes

2023-03-09 16:18 UTC, janezpodhostnik commented on engine/execution/computation/computer/result_collector.go
> +	if txn.lastTransactionInCollection {
invert to reduce nesting.

2023-03-09 19:13 UTC, pattyshack commented on engine/execution/computation/computer/computer.go
> +type collectionInfo struct {
note that i've added this struct back to group the collection fields

2023-03-09 19:13 UTC, pattyshack commented on engine/execution/computation/computer/computer.go
> -				"failed to execute %scollection at txnIndex %v: %w",
added prefix back to error

2023-03-09 21:59 UTC, janezpodhostnik approved these changes

2023-03-09 21:59 UTC, janezpodhostnik commented on engine/execution/computation/computer/computer.go
> -				"failed to execute %scollection at txnIndex %v: %w",
thank you

2023-03-11 01:37 UTC, SaveTheRbtz approved these changes

2023-03-13 17:03 UTC, pattyshack commented
bors merge

2023-03-13 17:43 UTC, merged