[Localnet] Fix semver for localnet builds
onflow/flow-go pull request #4591
Opened 2023-08-01 18:41 UTC by peterargue

There was a recent change to the node bootstrap that added validation of the `VERSION` flag to ensure it is semver compliant. This was added to support system event upgrades. However, on localnet, the version is hardcoded to a non-compliant string.

This PR update the default semver for localnet to use the default tag similar to how it works for integration tests.

If unset, version will look similar to this `v0.31.0-818-g6fa83a-localnetbuild`.

2023-08-08 13:04 UTC, janezpodhostnik requested changes

2023-08-10 12:13 UTC, janezpodhostnik approved these changes

2023-08-10 16:30 UTC, gomisha approved these changes
Thanks for the fix!

2023-08-10 16:52 UTC, Kay-Zee approved these changes

2023-08-10 17:38 UTC, merged