[EVM] Remove special EVM type
onflow/flow-go pull request #5791
Opened 2024-04-26 14:29 UTC by sideninja

Closes: #5414 

**💔 API Breaking Change**

Remove the special event type for evm: `evm.BlockExecuted` and `evm.TransactionExecuted` and make them be generic Flow event types: `A.{evm contract address}.EVM.TransactionExecuted` and `A.{evm contract address}.EVM.BlockExecuted`.

2024-04-26 15:47 UTC, janezpodhostnik approved these changes

2024-04-26 16:36 UTC, ramtinms approved these changes

2024-04-26 17:24 UTC, turbolent commented
Could you also please remove the EVM location again from the Go SDK?

2024-04-26 17:26 UTC, turbolent commented on fvm/evm/evm_test.go
> +				), string(blockEvent.Type))
Use `common.Location.TypeID()` instead. Same below

2024-04-26 17:26 UTC, turbolent commented on fvm/fvm_test.go
>  		}),
Keep using `common.Location.TypeID` here

2024-04-26 17:26 UTC, sideninja commented
> Could you also please remove the EVM location again from the Go SDK?

@m-Peter plans to

2024-04-26 18:11 UTC, sideninja commented on fvm/fvm_test.go
>  		}),
fixed

2024-04-26 20:43 UTC, turbolent commented
@sideninja Maybe forgot to push? There are no new commits

2024-04-29 09:33 UTC, m-Peter requested changes
@sideninja There are a couple more files that ideally should be updated:
- https://github.com/onflow/flow-go/blob/master/model/flow/event.go#L18
- https://github.com/onflow/flow-go/blob/master/model/events/parse.go#L28-L35
- https://github.com/onflow/flow-go/blob/master/model/events/parse_test.go#L46-L57

It would also be very useful to address this suggestion as well: https://github.com/onflow/flow-go/issues/5414#issuecomment-2071573662

We should also include the event definitions in the `EVM` contract itself, for example:

```cadence
access(all)
event BlockExecuted(
    height: UInt64,
    hash: String,
    ...
)

access(all)
event TransactionExecuted(
    blockHeight: UInt64,
    blockHash: String,
    hash: String,
    payload: String,
    ...
    logs: String
)
```

This will be helpful for other tools (such as the Cadence testing framework), to make use of these types cc @turbolent

2024-04-29 12:02 UTC, sideninja commented
> @sideninja Maybe forgot to push? There are no new commits

I did, sorry

2024-04-29 12:02 UTC, sideninja commented
> @sideninja There are a couple more files that ideally should be updated:
> 
> * https://github.com/onflow/flow-go/blob/master/model/flow/event.go#L18
> * https://github.com/onflow/flow-go/blob/master/model/events/parse.go#L28-L35
> * https://github.com/onflow/flow-go/blob/master/model/events/parse_test.go#L46-L57
> 
> It would also be very useful to address this suggestion as well: [#5414 (comment)](https://github.com/onflow/flow-go/issues/5414#issuecomment-2071573662)
> 
> We should also include the event definitions in the `EVM` contract itself, for example:
> 
> ```cadence
> access(all)
> event BlockExecuted(
>     height: UInt64,
>     hash: String,
>     ...
> )
> 
> access(all)
> event TransactionExecuted(
>     blockHeight: UInt64,
>     blockHash: String,
>     hash: String,
>     payload: String,
>     ...
>     logs: String
> )
> ```
> 
> This will be helpful for other tools (such as the Cadence testing framework), to make use of these types cc @turbolent

Great feedback, thanks. I like the idea of defining the event in the contract.

2024-04-29 12:47 UTC, m-Peter approved these changes
LGTM! :ok_hand:

2024-04-29 13:04 UTC, janezpodhostnik approved these changes

2024-04-29 15:42 UTC, turbolent approved these changes
Nice!

2024-04-29 21:37 UTC, merged