[Tools] Add a script to move checkpoint files
onflow/flow-go pull request #6143
Opened 2024-06-21 17:40 UTC by zhangchiqing

This PR adds a tool to move checkpoint files. It does both moving and renaming.

See the following example:
```
root@mainnettest-24-execution:/var/flow# bash move-checkpoint.sh test/checkpoint.001 test/root.checkpoint
Moved: /var/flow/test/checkpoint.001 -> /var/flow/test/root.checkpoint
Moved: /var/flow/test/checkpoint.001.000 -> /var/flow/test/root.checkpoint.000
Moved: /var/flow/test/checkpoint.001.001 -> /var/flow/test/root.checkpoint.001
Moved: /var/flow/test/checkpoint.001.002 -> /var/flow/test/root.checkpoint.002
Moved: /var/flow/test/checkpoint.001.003 -> /var/flow/test/root.checkpoint.003
Moved: /var/flow/test/checkpoint.001.004 -> /var/flow/test/root.checkpoint.004
Moved: /var/flow/test/checkpoint.001.005 -> /var/flow/test/root.checkpoint.005
Moved: /var/flow/test/checkpoint.001.006 -> /var/flow/test/root.checkpoint.006
Moved: /var/flow/test/checkpoint.001.007 -> /var/flow/test/root.checkpoint.007
Moved: /var/flow/test/checkpoint.001.008 -> /var/flow/test/root.checkpoint.008
Moved: /var/flow/test/checkpoint.001.009 -> /var/flow/test/root.checkpoint.009
Moved: /var/flow/test/checkpoint.001.010 -> /var/flow/test/root.checkpoint.010
Moved: /var/flow/test/checkpoint.001.011 -> /var/flow/test/root.checkpoint.011
Moved: /var/flow/test/checkpoint.001.012 -> /var/flow/test/root.checkpoint.012
Moved: /var/flow/test/checkpoint.001.013 -> /var/flow/test/root.checkpoint.013
Moved: /var/flow/test/checkpoint.001.014 -> /var/flow/test/root.checkpoint.014
Moved: /var/flow/test/checkpoint.001.015 -> /var/flow/test/root.checkpoint.015
Moved: /var/flow/test/checkpoint.001.016 -> /var/flow/test/root.checkpoint.016
Files moved successfully.
```

2024-06-21 19:59 UTC, peterargue approved these changes

2024-06-23 20:26 UTC, fxamacker requested changes
Maybe some code is missing?

This bash script doesn't move any files and always prints it was successful.

![image](https://github.com/onflow/flow-go/assets/33205765/8bf81b88-8153-43f0-b366-1b4cb7910938)

2024-06-24 04:19 UTC, zhangchiqing commented
Oh, good catch

2024-06-24 09:18 UTC, janezpodhostnik approved these changes

2024-06-24 09:18 UTC, janezpodhostnik commented on tools/move-checkpoint.sh
> +        echo "Moved: $(realpath "$file") -> $(realpath "$destination_file")"
```suggestion
        echo "Moving: $(realpath "$file") -> $(realpath "$destination_file")"
```
Just so its not misleading which file had problems if an error happens during `mv`.

2024-06-24 18:49 UTC, fxamacker approved these changes
Nice!  

Just ideas (feel free to ignore):
- maybe add a flag to use `mv -i` (for extra safety when used interactively)
- maybe use `sha256sum` in the script to confirm all the files didn't get modified/corrupted

2024-06-24 20:29 UTC, zhangchiqing commented
>maybe add a flag to use mv -i (for extra safety when used interactively)
Good point. I added a `--run` flag, to actually run the mv command, without this flag would be a preview of the files to be moved.

>maybe use sha256sum in the script to confirm all the files didn't get modified/corrupted
I'd like to keep the script simple for moving files around, the checksum should be done by separate tools.

2024-06-24 21:03 UTC, merged